### ISSUE TITLE
state должно быть приватным

### ISSUE THREAD

**Issue by RusNimex** [alexofechoes/PriceWatcher#1]
Лучше [свойство state](https://github.com/alexofechoes/PriceWatcher/blob/master/models/Watcher.php#L13) сделать приватным, т.к. оно должно меняться только внутри объекта. Соответственно понадобится геттер для него, чтоб пользователи смогли получить состояние этого объекта.

**Comment by alexofechoes** [comment]
3. Объект должен иметь публичное свойство state, которое может принимать одно из трех значений: warning, error и normal.

Меня это и смутило) Поэтому я его единственным и сделал public.

**Comment by RusNimex** [comment]
Да, здесь заложена ошибка, откровенно говоря. Если сомневаетесь, то хорошо бы написать это хотя в комментарии, чтоб потом обсудить с коллегами.
