### ISSUE TITLE
Нужно вернуть объект, чтобы иметь возможность с ним работать

### ISSUE THREAD

**Issue by RusNimex** [alexofechoes/PriceWatcher#2]
При использовании объекта PriceWatcher в [модели](https://github.com/alexofechoes/PriceWatcher/blob/master/models/Price.php#L58) он ничего не возвращает. Было бы хорошо, если бы PriceWatcher вернул себя, а модель, перед сохранением, проверяла бы статус этого объекта.

**Comment by alexofechoes** [comment]
Ок. поправлю.
